name: Jekyll site CI

on:
  push:
    branches: [ posting, gDocsAutomation ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # if you have/need it
        aws-region: us-east-2

    - name: Build the site in the jekyll/builder container
      env: 
        GDRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "apt-get update -y && apt-get install pandoc -y && chmod -R 777 /srv/jekyll && jekyll build"
    - name: "Deploy to AWS"
      run: aws s3 sync ${{ github.workspace }}//_site/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --acl public-read
